SELECT TSIANX.NUATTACH, CHAVEARQUIVO
FROM TSIANX
LEFT JOIN AD_ANEXOTSIATAETSIANX ON TSIANX.NUATTACH = AD_ANEXOTSIATAETSIANX.NUATTACH
LEFT JOIN TGFFIN FIN ON FIN.NUFIN = REPLACE( TSIANX.PKREGISTRO, '_Financeiro', '' )
WHERE TSIANX.NOMEINSTANCIA = 'Financeiro'
AND TSIANX.DHCAD >= trunc(sysdate)-11
AND AD_ANEXOTSIATAETSIANX.NUATTACH IS NULL
AND FIN.NUNOTA IS NOT NULL