SELECT TSIANX.NUATTACH
FROM TSIANX
    LEFT JOIN AD_ADANEXOTSIATAETSIANX ON TSIANX.NUATTACH = AD_ADANEXOTSIATAETSIANX.NUATTACH
WHERE TSIANX.NOMEINSTANCIA = 'Financeiro'
AND TSIANX.DHCAD >= trunc(sysdate)-1
AND AD_ADANEXOTSIATAETSIANX.NUATTACH IS NULL